src/userModel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from customUser.views import (
    home_screen_view,
    registration_view,
    logout_view,
    login_view,
    custom_user_update_my_data_view,
    custom_user_list_view,
    custom_user_add_view,
    custom_user_update_view,
    custom_user_delete_view,
)


urlpatterns = [
    path('admin/', admin.site.urls),    
    path("", home_screen_view, name="home"),
    path("register/", registration_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("login/", login_view, name="login"),
    path("user/", custom_user_update_my_data_view, name="customUserUpdateMyData"),
    path("list/", custom_user_list_view, name="customUserList"),
    path("add/", custom_user_add_view, name="customUserAdd"),
    path("update/<pk>/", custom_user_update_view, name="customUserUpdate"),
    path("delete/<pk>/", custom_user_delete_view, name="customUserDelete"),

        # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(
            template_name="password_reset_form.html"
        ), name="password_reset"
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/customUser/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    profile_picture = models.ImageField(default="default.jpg")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

src/customUser/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth import authenticate
from .models import CustomUser

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=60, help_text="Required. Add a valid email address"
    )

    class Meta:
        model = CustomUser
        fields = ("email", "password1", "password2")


class CustomUserAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ("email", "password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data["email"]
            password = self.cleaned_data["password"]
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("email","profile_picture")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("first_name","last_name","profile_picture")

src/customUser/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from customUser.forms import RegistrationForm, CustomUserAuthenticationForm, CustomUserChangeForm
from customUser.models import CustomUser
from django.contrib import messages

def custom_user_list_view(request):

    currentCustomUser = request.user
    if not currentCustomUser.is_staff:
        return redirect("home")

    template = "custom_user_list.html"

    custom_user_list = CustomUser.objects.all()

    context = {"custom_user_list": custom_user_list}
    return render(request, template, context)

def custom_user_add_view(request):

    currentCustomUser = request.user
    if not currentCustomUser.is_staff:
        return redirect("home")

    template = "custom_user_add.html"
    context = {}

    if request.POST:
        try:
            form = RegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                email = form.cleaned_data.get("email")
                raw_password = form.cleaned_data.get("password1")
                custom_user = authenticate(email=email, password=raw_password)

                messages.success(request, "User was created")
            else:
                context["form"] = form
        except Exception as e:
            messages.warning(
                request, "The user could not be created: Error: {}".format(e)
            )
    else:
        form = RegistrationForm()
        context["form"] = form
    return render(request, template, context)    

def custom_user_update_view(request, pk):

    currentCustomUser = request.user
    if not currentCustomUser.is_staff:
        return redirect("home")  

    template = "custom_user_update.html"          

    custom_user = get_object_or_404(CustomUser, pk=pk)
    if request.method == "POST":

        form = CustomUserChangeForm(request.POST, instance=custom_user)
        try:
            if form.is_valid():
                form.save()
                form.initial = {
                    "first_name": request.POST["first_name"],
                    "last_name": request.POST["last_name"],
                }
                messages.success(request, "Your account has been updated")

        except Exception as e:
            messages.warning(request, "The account was not saved due to an error")
    else:
        form = CustomUserChangeForm(
            instance=custom_user,
            initial={
                "first_name": custom_user.first_name,
                "last_name": custom_user.last_name,
            },
        )

    context = {"form": form, "custom_user": custom_user}
    return render(request, template, context)   

def custom_user_delete_view(request, pk):

    currentCustomUser = request.user
    if not currentCustomUser.is_staff:
        return redirect("home")

    template = "custom_user_delete.html"

    custom_user = get_object_or_404(CustomUser, pk=pk)

    try:
        if request.method == "POST":
            form = CustomUserChangeForm(request.POST, instance=custom_user)
            custom_user.delete()
            return redirect("customUserList") 
        else:
            form = CustomUserChangeForm(
                instance=custom_user,
                initial={
                    "email": custom_user.email,
                    "first_name": custom_user.first_name,
                    "last_name": custom_user.last_name,
                },
            )
    except Exception as e:
        messages.warning(
            request, "The account could not be deleted: Error: {}".format(e)
        )

    context = {"form": form, "custom_user": custom_user}
    return render(request, template, context) 

def home_screen_view(request):
    template = "home.html"
    context = {}

    users = CustomUser.objects.all()
    context["users"] = users

    return render(request, template, context)


def registration_view(request):

    currentCustomUser = request.user
    if not currentCustomUser.is_staff:
        return redirect("home")

    template = "register.html"
    context = {}

    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect("home")
        else:
            context["registration_form"] = form
    else:
        form = RegistrationForm()
        context["form"] = form
    return render(request, template, context)


def logout_view(request):
    logout(request)
    return redirect("home")


def login_view(request):

    customUser = request.user
    if customUser.is_authenticated:
        return redirect("home")

    template = "login.html"
    context = {}

    form = CustomUserAuthenticationForm()

    if request.POST:
        form = CustomUserAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            customUser = authenticate(email=email, password=password)

            if customUser:
                login(request, customUser)
                return redirect("home")
        else:
            form = CustomUserAuthenticationForm(
                initial={ "email": "",}
            )

    context["form"] = form
    return render(request, template, context)


def custom_user_update_my_data_view(request):

    if not request.user.is_authenticated:
        return redirect("login")

    template = "custom_user_update_my_data.html"

    context = {}
    
    if request.POST:
        try:
            form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():          
                form.save()
                messages.success(request, "Your account has been updated")
        except Exception as e:
            messages.warning(
                request, "The account could not be updated: Error: {}".format(e)
            )


    form = CustomUserChangeForm(
        initial={
            "email": request.user.email,
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
            "profile_picture": request.user.profile_picture,
        }
    )

    context["form"] = form
    return render(request, template , context)

src/customUser/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>This is the title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'snippets/header.html' %}
</head>

<body>



    <!--The Body-->

    <style type="text/css">
        .avatar {
            max-width: 40px;
            min-width: 40px;
            height: 40px;
            overflow: hidden;
            border-radius: 50%;
            margin-right: 10px;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: 10px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="username"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .form-signin input[type="text"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .h3 {
            text-align: center;
        }

        .main {
            min-height: 100vh;
            height: 100%;
        }
    </style>

    <div class="main">
        {% block content%}

        {% endblock content %}
    </div>

    <!--End Body-->
    {% include 'snippets/footer.html' %}
</body>

</html>

src/customUser/templates/custom_user_add.html
{% extends 'base.html' %}


{% block content %}

<form class="form-signin" method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Add a User</h1>

    {% include 'snippets/message.html' %}

    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
        autofocus>

    <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

    <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password"
        required>

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Add user</button>

</form>


{% endblock content %}

src/customUser/templates/custom_user_delete.html
{% extends 'base.html' %}

{% block content %}

<form class="form-signin" method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">User</h1>

    {% include 'snippets/message.html' %}

    <h5 class="font-weight-normal">Email</h5>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus
        value="{{form.initial.email}}">

    <h5 class="font-weight-normal">First name</h5>
    <input type="text" name="first_name" id="inputFirst_name" class="form-control" placeholder="Firstname"
        value="{{form.initial.first_name}}">

    <h5 class="font-weight-normal">Last name</h5>
    <input type="text" name="last_name" id="inputLast_name" class="form-control" placeholder="Lastname"
        value="{{form.initial.last_name}}">

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Delete</button>

</form>


{% endblock content %}

src/customUser/templates/custom_user_list.html
{% extends 'base.html' %}

{% block content %}

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope=col">Image</th>
            <th scope=col">Email</th>
            <th scope=col">First name</th>
            <th scope=col">Last name</th>
            <th scope=col">Edit</th>
            <th scope=col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for custom_user in custom_user_list %}
        <tr>
            <td> <img class="avatar" src="{{ custom_user.profile_picture.url }}" alt="..." class="img-fluid"></td>
            <td>{{custom_user.email}}</td>
            <td>{{custom_user.first_name}}</td>
            <td>{{custom_user.last_name}}</td>
            <td><a href="{% url 'customUserUpdate' pk=custom_user.pk %}" </a><button
                        class="btn btn-primary ">Update</button>
            </td>
            <td><a href="{% url 'customUserDelete' pk=custom_user.pk %}" </a><button
                        class="btn btn-primary ">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

src/customUser/templates/custom_user_update.html
{% extends 'base.html' %}

{% block content %}


<form class="form-signin" enctype='multipart/form-data' method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Account</h1>
    <br>
    <h5 class="h5 mb-3 font-weight-normal">{{custom_user.email}}</h5>

    {% include 'snippets/message.html' %}

    <h5 class="font-weight-normal">First name</h5>
    <input type="text" name="first_name" id="inputFirst_name" class="form-control" placeholder="Firstname"
        value="{{form.initial.first_name}}">

    <h5 class="font-weight-normal">Last name</h5>
    <input type="text" name="last_name" id="inputLast_name" class="form-control" placeholder="Lastname"
        value="{{form.initial.last_name}}">

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Save changes</button>

</form>

<div class=d-flex flex-column>
    <a class="m-auto" href="{% url 'password_change' %}">Change password</a>
</div>





{% endblock content %}

src/customUser/templates/custom_user_update_my_data.html
{% extends 'base.html' %}

{% block content %}


<form class="form-signin" enctype='multipart/form-data' method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Account</h1>

    {% include 'snippets/message.html' %}

    <div class="avatar"><img src="{{ form.initial.profile_picture.url }}" alt="..." class="img-fluid">
    </div>

    <h5 class="font-weight-normal">Email</h5>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus
        value="{{form.initial.email}}">

    <h5 class="font-weight-normal">First name</h5>
    <input type="text" name="first_name" id="inputFirst_name" class="form-control" placeholder="Firstname"
        value="{{form.initial.first_name}}">

    <h5 class="font-weight-normal">Last name</h5>
    <input type="text" name="last_name" id="inputLast_name" class="form-control" placeholder="Lastname"
        value="{{form.initial.last_name}}">

    <div class="form-row field-profile_picture" enctype='multipart/form-data'>
        <div>
            <label class="required" for="id_profile_picture">Profile picture:</label>
            <p class="file-upload">Currently: <a>{{form.initial.profile_picture}}</a><br>
                <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture"></p>
        </div>
    </div>


    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Save changes</button>

</form>

<div class=d-flex flex-column>
    <a class="m-auto" href="{% url 'password_change' %}">Change password</a>
</div>

{% endblock content %}

src/customUser/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap
        example.
        It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">
    <div class="d-flex flex-column">
        <h4>Registered users:</h4>
        {% for user in users %}
        <p>{{user}}</p>
        {% endfor %}
    </div>
</div>

{% endblock content%}

src/customUser/templates/login.html
{% extends 'base.html' %}

{% block content %}


<form class="form-signin" method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Login</h1>

    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
        autofocus>

    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>

</form>

<div class="d-flex flex-column">
    <a class="m-auto" href="{% url 'password_reset' %}">Reset password</a>
</div>

{% endblock content %}

src/customUser/templates/password_change.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" class="form-signin">{% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password"
        required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1"
        required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password"
        id="id_new_password2" required="true">

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
</form>



{% endblock %}

src/customUser/templates/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="d-flex flex-column">
        <p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a>
            now.</p>
    </div>
</div>

{% endblock %}

src/customUser/templates/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="d-flex flex-column">
        <p class="m-auto p-2">
            We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.
        </p>
        <p class="m-auto p-2">
            If you don't receive an email, please make sure you've entered the address you registered with,
            and check your spam folder.
        </p>
        <p class="m-auto p-2"><a href="{% url 'home' %}">Return to home page</a></p>
    </div>
</div>

{% endblock %}

src/customUser/templates/password_reset_email.html
{% autoescape off %}
For at nulstille dit password for din bruger konto {{ user.email }},
følg venligst nedenstående link:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Med venlig hilsen,
Det lille yoga hold
{% endautoescape %}

src/customUser/templates/password_reset_form.html
{% extends 'base.html' %}


{% block content %}


<form method="POST" class="form-signin">{% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Send reset email</button>
</form>



{% endblock %}

src/customUser/templates/register.html
{% extends 'base.html' %}


{% block content %}



<form class="form-signin" method="post">{% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Register a User</h1>

    {% include 'snippets/message.html' %}

    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
        autofocus>

    <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

    <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password"
        required>

    {% include 'snippets/error_messages.html' %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

</form>


{% endblock content %}